ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),
    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),

    # url(r'^blog/', include('blog.urls')),
    #(?P<all_items>.*)
    #(?P<id>\d+)
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
	url(r'^contact/thankyou/', 'contacts.views.thankyou',name='thankyou'),
    url(r'^contact/', 'contacts.views.contactview',name='contact'),
) 


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/contacts/models.py
from django.db import models
from django.forms.widgets import *
from django.core.mail import send_mail, BadHeaderError
from django import forms

# Create your models here.
# A simple contact form with four fields.
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    topic = forms.CharField()
    message = forms.CharField(widget=Textarea())

ecommerce/contacts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from contacts.models import ContactForm
from django.template import RequestContext, Context
#from django import newforms as forms
#from django.newforms.widgets import *
from django import forms
from django.forms.widgets import *
from django.core.mail import send_mail, BadHeaderError

# Create your views here.

def contactview(request):
	subject = request.POST.get('topic', '')
	message = request.POST.get('message', '')
	from_email = request.POST.get('email', '')

	if subject and message and from_email:
		try:
			send_mail(subject, message, from_email, ['change@this.com'])
			return HttpResponseRedirect('/contact/thankyou/')
		except BadHeaderError:
       			return HttpResponse('Invalid header found.')
      	else:
			return render_to_response('contacts.html', {'form': ContactForm()})
		
	return render_to_response('contacts.html', {'form': ContactForm()},
			RequestContext(request))

def thankyou(request):
	return render_to_response('thankyou.html')

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}{% endblock %}YU ESTORE</title>

    {% load staticfiles %}
    <!-- <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}' />
    <link rel='stylesheet' href='{% static "css/bootstrap-theme.min.css" %}' /> -->

      <!-- Latest compiled and minified CSS 
  --> 
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">


	<!-- Optional theme 
 -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar-static-top/navbar-static-top.css" rel="stylesheet">
    <style>
    .alert-top-message {
        margin-bottom: 0px;
        border-radius: 0px;
        text-align: center;
        background-color: #DBDBDB;
     
    }
    .alert-top-message h3{
        margin: 0 auto;
    }

    .modal-dialog {
      margin-top: 15%;
    }
    {% block styles %}
    {% endblock %}

    .background_img_thumb {
        width:100%; 
        height:100%;
        background-image: url("{% static 'img/placeholder.svg' %}");
        background-size:cover;
        background-repeat:no-repeat; 
        background-position:center;
    }


    </style>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body>
  {% if request.session.marketing_message %}
  <div class='alert alert-top-message alert-dismissible' role='alert'>
    <button id='marketing-message-btn' type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <div class="container">
        <h3>{{ request.session.marketing_message|safe }}</h3>
      </div>
  </div>
  {% endif %}

  {% include 'navbar.html' %}

    {% block jumbotron %}
    {% endblock %}

  


    <div class="container">
         {% if messages %}
            {% for message in messages %}
            <div class='alert {% if "success" in message.tags %}alert-success{% elif "warning" in message.tags%}alert-warning{% elif "error" in message.tags %}alert-danger{% endif %} alert-dismissible' role='alert'>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
               
                {% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
                
          </div>
          {% endfor %}
      {% endif %}
    {% block content %}

    {% endblock %}

    </div> <!-- /container -->

    {% include "modal.html" %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script>
      $(document).ready(function(){
        $("#marketing-message-btn").click(function(){
         $.ajax({
              type: "POST",
              url: "{% url 'dismiss_marketing_message' %}",
              data: {
                "dimiss-marketing": true,
                "csrfmiddlewaretoken": "{{ csrf_token }}",
              },
              success: function(data){
              },
              error: function(){
                alert("Error! Something wrong. Please try again later")
              },
           });
        });
    
        {% if not request.user.is_authenticated and not request.session.email_added_marketing and not "accounts" in request.get_full_path %}
        function showModal(){
          $("#marketingModal").modal("show");
          // setTimeout(showModal, 5000);
        }
        // showModal()
        setTimeout(showModal, 5000);
        $("#sendMarketingForm").click(function(e){
          e.preventDefault()
          var mForm = $("#sendForm").serialize()
         $.ajax({
              type: "POST",
              url: "{% url 'ajax_email_signup' %}",
              data: mForm,
              success: function(data){
                // console.log(data)
                $("#modalMessage").html("<p>" + data + "</p>")
                 $("#marketingModal").modal("hide");
              },
              error: function(data){
                // console.log(data)
                // console.log(data.responseJSON)
                var obj = data.responseJSON
                // console.log(obj)
                // console.log(obj.email)
                $("#modalMessage").html("<p style='color:red;'>" + obj.email + "</p>")
              },
           });
        });
        {% endif %}


        

    });


  </script>


	<script>
	$(document).ready(function(){
		{% block jquery %}{% endblock%}
	});

	</script>
  </body>
</html>

ecommerce/templates/contacts.html
{% block fulltitle %}Contact me!{% block title %}{% endblock %}{% endblock %}

{% block header %}
<h3> header of course</h3>
{% endblock %}

{% block extrahead %}
{% endblock %}

{% block content-wrap %}
        <div id="contact_wrap">

        <div id="contact" class="clearfix">
            <div id="c_form">
                <br /><br />
                <form name="theform" action="." method="post" id="theform">
                    <div id="name_email">

                        <label id="id_name">Name:</label>
                        <input type="text" name="name" value="" id="name" />
                        <label id="id_email">Email:</label>
                        <input type="text" name="email" value="" id="Email" />
                    </div><!-- end name_email -->
                    <div id="message">
                        <label id="id_message">Message:</label>
                        <textarea name="message" rows="8" cols="37"></textarea>

                    </div><!-- end message -->
                    <div id="submit">
                        <input type="image" src="http://path/to/submitbutton.png" onclick="YY_checkform('theform','name','#q','0','Field \'name\' is empty.','Email','#S','2','Field \'Email\' appears not to be valid.','message','2','1','Field \'message\' is empty.');return document.MM_returnValue" />
                    </div><!-- end submit -->
                    <input class="hidden" type="hidden" name="topic" value="Home : Contact Form Submission" id="subject" />
                </form>

            </div><!-- end c_form -->
        </div><!-- end contact -->

    </div><!-- end contact_wrap -->

{% endblock %}

ecommerce/templates/form.html
{% extends "base.html" %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3' style='margin-top: 50px;'>
<h1>{{ form_title }}</h1>
<form method='POST' action=''>{% csrf_token %}
{{ form.as_p }}


<input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' class='btn btn-default' />
&nbsp;&nbsp;
<a href="/accounts/register">Not have an account yet? Signup now!</a>
</form>
</div>

{% endblock %}

ecommerce/templates/modal.html
<!--
 ads
-->

ecommerce/templates/navbar.html
  <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Yu eCommerce</a>
        </div>
        <div class="navbar-collapse collapse">

          <form class="navbar-form navbar-left" role="search" action='/s/'>
            <div class="form-group">
          <input type="text" class="form-control" name='q' placeholder="Search Product Title">
            </div>
          <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'products' %}">Products</a></li>
            <li><a href="{% url 'cart' %}">Cart <span class="badge">{% if not request.session.items_total %} 0 {% else %} {{ request.session.items_total }} {% endif%}</span></a></li>
            {% if user.is_authenticated %}
            <li><a href="#">Account</a></li>
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
			<li><a href="{% url 'contact' %}">Feedback</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

ecommerce/templates/thankyou.html
{% block billboard %}Services{% endblock %}
{% block title %}Services{% endblock %}

{% block header %}
<h3> header of course</h3>
{% endblock %}

{% block content %}
<h3>Contact Information</h3>

<p>Thank you for contacting us.</p>

<p>We will attempt to get back to you within 48 hours</p>



{% endblock %}